server {
  listen 80;
  server_name localhost;
  return 308 https://127.0.0.1:3443$request_uri;
}

server {
  listen 443 ssl;
  server_name localhost;
  ssl_certificate /etc/nginx/tls/localhost.crt;
  ssl_certificate_key /etc/nginx/tls/localhost.key;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_session_tickets off;

  location / {
    proxy_pass http://api-remediated:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $remote_addr;
  }
}
